#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

rm -rf processor? log.*

decomposePar -region fluid && decomposePar -region solid

#runApplication $application

mpirun -np 6 $application -parallel > log.cht

# ----------------------------------------------------------------- end-of-file

